export const SUBJECT_COLORS: Record<string, string> = {
  "Prerequisites of Engineering Mathematics": "#f472b6",
  "Discrete Mathematics": "#818cf8",
  "Probability & Statistics": "#34d399",
  "Linear Algebra": "#60a5fa",
  "Calculus & Optimization": "#a78bfa",
  "Basic of Computer System": "#94a3b8",
  "Fundamentals of C Language": "#f97316",
  "C Programming": "#fb923c",
  "Data Structures & Programming": "#22d3ee",
  "Algorithms": "#4ade80",
  "Theory of Computation": "#e879f9",
  "Digital Logic": "#facc15",
  "Computer Organization & Architecture": "#f87171",
  "Computer Networks": "#38bdf8",
  "Operating System": "#6ee7b7",
  "Compiler Design": "#c084fc",
  "Database Management System": "#fda4af",
  "General Aptitude": "#fed7aa",
  "Verbal Aptitude": "#bbf7d0",
};

export const SUBJECT_COLORS_BY_ID: Record<string, string> = {
  prereq_math: "#f472b6",
  discrete_math: "#818cf8",
  prob_stats: "#34d399",
  linear_algebra: "#60a5fa",
  calculus: "#a78bfa",
  basic_cs: "#94a3b8",
  fund_c: "#f97316",
  c_prog: "#fb923c",
  data_structures: "#22d3ee",
  algorithms: "#4ade80",
  toc: "#e879f9",
  digital_logic: "#facc15",
  coa: "#f87171",
  cn: "#38bdf8",
  os: "#6ee7b7",
  compiler: "#c084fc",
  dbms: "#fda4af",
  gen_aptitude: "#fed7aa",
  verbal: "#bbf7d0",
};

export const SUBJECT_SHORT: Record<string, string> = {
  "Prerequisites of Engineering Mathematics": "Pre-Math",
  "Discrete Mathematics": "DM",
  "Probability & Statistics": "P&S",
  "Linear Algebra": "LA",
  "Calculus & Optimization": "C&O",
  "Basic of Computer System": "BCS",
  "Fundamentals of C Language": "FC",
  "C Programming": "CP",
  "Data Structures & Programming": "DS",
  "Algorithms": "Algo",
  "Theory of Computation": "TOC",
  "Digital Logic": "DL",
  "Computer Organization & Architecture": "COA",
  "Computer Networks": "CN",
  "Operating System": "OS",
  "Compiler Design": "CD",
  "Database Management System": "DBMS",
  "General Aptitude": "GA",
  "Verbal Aptitude": "VA",
};

export const SUBJECT_SHORT_BY_ID: Record<string, string> = {
  prereq_math: "Pre-Math",
  discrete_math: "DM",
  prob_stats: "P&S",
  linear_algebra: "LA",
  calculus: "C&O",
  basic_cs: "BCS",
  fund_c: "FC",
  c_prog: "CP",
  data_structures: "DS",
  algorithms: "Algo",
  toc: "TOC",
  digital_logic: "DL",
  coa: "COA",
  cn: "CN",
  os: "OS",
  compiler: "CD",
  dbms: "DBMS",
  gen_aptitude: "GA",
  verbal: "VA",
};
